### ISSUE TITLE
bash: ./install.sh: Permission denied

### ISSUE THREAD

**Issue by umair701** [ItsMeAbhishekRai/Termux-All-Packages-Install#1]
In Termux, I can not  install all the packages. As I can not run this command./install.sh. The above error message came up. Could someone guide me please, thank you. 

Ozzy

**Comment by Bluehathacker** [comment]
Use command bash install.sh hit enter all packages are easily install

**Comment by umair701** [comment]
WoW It works like a charm, many thanks. 

Ozzy

**Comment by haouarhack** [comment]
./install.sh error ... but   $sh install.sh ... work Good

**Comment by ItsMeAbhishekRai** [comment]
Oky Thanks
